### ISSUE TITLE
Inference issues?

### ISSUE THREAD

**Issue by adamConnerSax** [isovector/polysemy#17]
I don't think I have a concrete issue.  Just an observation:

I have some functions which returned the freer-simple ```Eff effs x``` monad, defined in a let statement in do block, returning ```Eff effs' x``` where all the constraints on ```effs``` are also constraints satisfied by ```effs'```.  These functions did not have type signatures.  E.g. (very schematic example!  The real case has much more...noise between the definition of myOtherFunc and where/how it is used)  

```
f :: Int -> (Member MyEff effs) => Eff effs ()
f = ...

myFunc :: (Member MyEff effs) => Eff effs ()
my = do
  let myOtherFunc = f 2
  myOtherFunc
```
With freer-simple, these compiled.  After switching to polysemy, some of them do not, basically because they fail to unify the ```effs``` in the do block and ```effs``` being returned from the function? I think?  The error message is about a missing constraint of the form ```(Member MyEff effs0)``` on the at-that-point ambiguous `effs0` at the line where the ```let``` is.

What's notable, is that if I enable PartialTypeSignatures and then put a type signature on each function of the form ```let myOtherFunc :: _```, many of these now compile fine.  Which is confusing. What does PartialTypeSignatures know that is a secret from the rest of ghc?

I don't think I can cook up an example because I don't really know why it happens sometimes and not others and the code where it happens is way too messy and full of other things to be of any use figuring this out, I think. So feel free to close this on account of it's not specific enough.  But I thought you might find the information helpful!

**Comment by isovector** [comment]
Do you have `-XMonoLocalBinds` and/or `-XNoMonomorphismRestriction` turned on (bear in mind that they might be implicitly enabled via other extensions)? AFAICT there shouldn't be any differences between `freer-simple` and `polysemy` in terms of type inference.

Try explicitly setting `{-# LANGUAGE MonomorphismRestriction, MonoLocalBinds #-}` as the _last_ language extensions in your file, and I'd bet dollars to donuts the issue goes away.

**Comment by adamConnerSax** [comment]
Huh. But what if I need the NoMonomorphism restriction enabled?  I guess at some point I am getting greedy and I can just work around it. 
I'm doing some data-analysis stuff with Frames and the signatures there get very very long so I usually hope that inference will suffice.  But I think that means the the Monomorphism restriction sometimes bites because I'm using the same polymorphic function at different types in the same do block?  I'm in over my head trying to figure this out.

**Comment by isovector** [comment]
I'm not sure I can help in that case; these are fundamental limitations in Haskell you're bumping into, and `freer-simple` would have the same problems. Maybe I can add some documentation?

**Comment by adamConnerSax** [comment]
Documentation might be helpful.  
I wish I had a clearer picture of my path from where it was compiling with ```freer-simple``` and then not with ```polysemy``` so I could figure out what else had changed.  There must have been another change that helped the inference along but I can't figure out what it could have been.  
And the ```PartialTypeSignatures``` solution is not so painful.
Best to leave it at that for now!

**Comment by isovector** [comment]
Actually come to think of it, maybe I can. I'm planning on releasing a typechecker plugin that can help fill in the "obvious" type parameters in `send`s. Presumably the plugin could solve this at the same time.

**Comment by adamConnerSax** [comment]
That would be cool!  And helpful. Thanks!

**Comment by isovector** [comment]
Give this a spin: [`polysemy-plugin`](https://hackage.haskell.org/package/polysemy-plugin) --- it should automatically disambiguate most ambiguous uses of effects, aka dramatically improve type inference.
