### ISSUE TITLE
Doesn't play nicely with fundeps?

### ISSUE THREAD

**Issue by adamConnerSax** [isovector/polysemy#18]
I've got a logging effect <https://github.com/adamConnerSax/knit-haskell/blob/master/src/Knit/Effects/Logger.hs>.  I'd like to provide something like (where ```log :: Member (Logger a) effs => a -> Semantic effs ()```)

```haskell
import Control.Monad.Log
import Polysemy
instance (Member (Logger a) effs) => MonadLog a (Semantic r) where
  logMessageFree inj = mapM_ log (inj $ pure @[])
```
(mind you, I've no idea of that's a correct instance but that's neither here nor there for this issue) and I get an error because of the functional dependency in MonadLog:
```
• Illegal instance declaration for ‘ML.MonadLog a (Semantic effs)’
        The liberal coverage condition fails in class ‘ML.MonadLog’
          for functional dependency: ‘m -> message’
        Reason: lhs type ‘Semantic effs’ does not determine rhs type ‘a’
        Un-determined variable: a
    • In the instance declaration for ‘ML.MonadLog a (Semantic effs)’
```
  Which is fair since I could have mutiple logger instances, etc.  So I can't write this instance, right?
But then I have a problem, or might.  Because what should people do with an existing function which has that MonadLog constraint?  I tried also to write an instance like
```haskell
instance (MonadLog a m, Member (Lift m) effs) => MonadLog a (Semantic effs) where
  logMessageFree inj = sendM @m $ logMessageFree inj
```
but that has the same issue, plus a new, inference-related one (even with the TypeApplication):
```
 • Ambiguous use of effect 'P.Lift'
      Possible fix:
        add (Member (P.Lift m0) effs) to the context of 
          the type signature
      If you already have the constraint you want, instead
        add a type application to specify
          'm0' directly
    • In the ambiguity check for an instance declaration
      To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
      In the instance declaration for ‘ML.MonadLog a (Semantic effs)’
```

I guess I can give this particular issue up but I am wondering a bit about the general interoperability story when it comes to supporting effects that are baked into existing code via a typeclass constraint where that class has a fundep.

**Comment by isovector** [comment]
Yup --- fundeps are fundamentally not going to work with `Semantic`. I prefer to think of this as a "feature" rather than a "bug" but YMMV.

The solution is to embrace the way of the free monads. Give up on MTL-esque constraints, and build your own effects. In particular, you might want `Polysemy.Trace` if you just want to write messages out; or `Polysemy.Output` if you want to emit more structure.

What functions do you need that have a `MonadLog` constraint? Is there a reason you can't replace those with `Member MyLoggingEffect r`?

**Comment by adamConnerSax** [comment]
Yeah.  I more or less understand that. And I also think of it as feature not bug.
I'm happy to embrace it when I am in control of all the code.
The library I am working on, with this logging effect in it, is an attempt to emulate a small bit of the Rmarkdown experience, that is, the ability to intersperse computational code and document building in one app.  So I'm supplying the wrapping around Pandoc (thus my earlier PandocIO question) and Blaze and Lucid and and supplying some other standard effects: Logging and Randomness.  Logging because it's often useful, especially in trying-to-get-something-done-quick kind of setting and randomness because it's important in all sorts of numerical algos.  
The thing I am wondering about, is what happens when someone wants to use my library with some other library that relies on "MTL-esque" constraints?  
Is that just always a problem when people use different effects libraries or are there ways to mitigate that?
Like, for the [RandomFu](https://github.com/adamConnerSax/knit-haskell/blob/master/src/Knit/Effects/RandomFu.hs)  effect (my numerical stuff happens to use random-fu), I was able to write a ```MonadRandom``` instance like
```haskell
instance (Member RandomFu.Random r) => MonadRandom (Semantic r)
``` 
which then allows interoperation with a MonadRandom constraint.
I was hoping for the same story with logging, though there are more logging libraries so maybe specific interoperation is less important.
Anyway, just trying to think all that through as I build this thing out.

**Comment by adamConnerSax** [comment]
I think this one can be closed as well, since I've sorted out all of these issues, one way or another.
