### ISSUE TITLE
[Noob Questions] Trying to make sense of effect composition and running

### ISSUE THREAD

**Issue by sandoichi** [isovector/polysemy#19]
I'm trying to understand how to use this library properly, and I've hit a couple of scenarios that I'm uncertain of.

Given this example effect type:
```
{-# LANGUAGE TemplateHaskell #-}

module Test where

import Polysemy
import Polysemy.Trace
import System.Directory

data Test m a where
  DoTest :: Test m ()

makeSemantic ''Test
```

1) If I have a "runE" function that needs to use some other effect, is it normal to lift that other effect into the resulting Semantic that gets produced?

ex:  
```
runTestIO :: ( Member (Lift IO) r
             , Member Trace r
             )
          => Semantic (Test ': r) a -> Semantic r a
runTestIO =
  interpret $ \case
    DoTest -> do
      trace $ "This is a test"
      sendM $ copyFile "C:\\test.txt" "D:\\test.txt"
```

Should `Trace` show up here in the type signature? Or is it expected to `runTraceIO` in my handler and only get down to IO?

2) If it is OK to add effects in these run methods, how can I properly run them whenever I want to get to IO ?

Given the following code:
```
test1 :: (Member (Lift IO) r, Member Trace r)
      => Semantic (Test ': r) a -> Semantic r a
test1 x = runTestIO x

test2 :: Member (Lift IO) r
      => Semantic (Trace ': r) a -> Semantic r a
test2 x = runTraceIO x

testToIO :: Semantic (Test ': Trace ': Lift IO ': r) a
            -> IO a
testToIO x = do
  let a = test1 x
  let b = test2 a
  runM b -- This doesn't compile
```

 I'm trying to break apart the nested effects step by step here to understand them, but I'm coming up a bit short. `b` should have the type `Member (Lift IO) r => Semantic r a`, but that doesn't seem to satisfy the input to `runM`, which is `Monad m => Semantic '[Lift m] a`

 3) How does `Semantic '[Lift m] a` differ from `Member (Lift m) r => Semantic r a` ? Are there certain situations in which one form is more appropriate than the other? I'm fairly new to Haskell, and this syntax isn't something that I've encountered before :)

 Thanks

**Comment by isovector** [comment]
1: `runTestIO` looks perfectly fine to me! You _can_ run the `Trace` effect in your handler, but it's largely a matter of choice. My suggestion would be to handle it if it's an integral part of your interpretation (for example, if you want to use a local piece of state in your interpreter, run the `State` effect immediately). If it's not an integral part, or if you can imagine someone later being unhappy with your choice of the interpreter, add it as a `Member` constraint.

2: I think your problem is caused by the `let`s. In Haskell, `let`s will take a more general type than you want. try  writing `runM . test2 . test1 $ x` directly.

3: `Semantic '[Lift m] a` is saying the _only_ effect you have is a `Lift m`. `Member (Lift m) r => Semantic r a` says you definitely have a `Lift m` effect, _but you might also have others!_. You should always prefer to use the `Member (Lift m) r` version!

As for the syntax, the relevant search keyword you want is `DataKinds` :)

**Comment by sandoichi** [comment]
Thanks for the helpful response!

I've tried your suggestion to remove the `let`s but still have issues.

```
testToIO :: Semantic (Test ': Trace ': Lift IO ': r) a -> IO a
testToIO x = runM . test2 . test1 $ x
```

```
src\Test.hs:35:37: error:
    * Couldn't match type `r' with '[]
      `r' is a rigid type variable bound by
        the type signature for:
          testToIO :: forall (r :: [(* -> *) -> * -> *]) a.
                      Semantic (Test : Trace : Lift IO : r) a -> IO a
        at src\Test.hs:34:1-62
      Expected type: Semantic '[Test, Trace, Lift IO] a
        Actual type: Semantic (Test : Trace : Lift IO : r) a
    * In the second argument of `($)', namely `x'
      In the expression: runM . test2 . test1 $ x
      In an equation for `testToIO':
          testToIO x = runM . test2 . test1 $ x
    * Relevant bindings include
        x :: Semantic (Test : Trace : Lift IO : r) a
          (bound at src\Test.hs:35:10)
        testToIO :: Semantic (Test : Trace : Lift IO : r) a -> IO a
          (bound at src\Test.hs:35:1)
   |
35 | testToIO x = runM . test2 . test1 $ x
   |                                     ^
```

  I then thought about my type signature, particularly the input that I told it to expect `Semantic (Test ': Trace ': Lift IO ': r) a ` and realized that this isn't quite accurate. My `x` input would only have `Member Test`, so I changed it around:

```
testToIO3 :: Member Test r => Semantic r a -> IO a
testToIO3 x = runM $ test2 $ test1 x
```

```
src\Test.hs:44:36: error:
    * Could not deduce: r ~ '[Test, Trace, Lift IO]
      from the context: Member Test r
        bound by the type signature for:
                   testToIO3 :: forall (r :: [(* -> *) -> * -> *]) a.
                                Member Test r =>
                                Semantic r a -> IO a
        at src\Test.hs:43:1-50
      `r' is a rigid type variable bound by
        the type signature for:
          testToIO3 :: forall (r :: [(* -> *) -> * -> *]) a.
                       Member Test r =>
                       Semantic r a -> IO a
        at src\Test.hs:43:1-50
      Expected type: Semantic '[Test, Trace, Lift IO] a
        Actual type: Semantic r a
    * In the first argument of `test1', namely `x'
      In the second argument of `($)', namely `test1 x'
      In the second argument of `($)', namely `test2 $ test1 x'
    * Relevant bindings include
        x :: Semantic r a (bound at src\Test.hs:44:11)
        testToIO3 :: Semantic r a -> IO a (bound at src\Test.hs:44:1)
   |
44 | testToIO3 x = runM $ test2 $ test1 x
   |                                    ^
   ```

  `test1` has the signature 
  ```
  test1 :: (Member (Lift IO) r, Member Trace r)
      => Semantic (Test ': r) a -> Semantic r a
 ```
 so wouldn't that be proof to the compiler that `Lift IO` and `Trace` are inside of `r` after `test1` returns?

**Comment by sandoichi** [comment]
Now I'm even more confused.

I have an example that does not compile:
```
test :: Member Test r => Semantic r () -> IO ()
test = runM . runTraceIO . runTestIO
```
But, this compiles
```
test :: IO ()
test = runM . runTraceIO . runTestIO $ doTest
```
And the type of `doTest` is 
`doTest :: Member Test r => Semantic r ()`
which matches exactly what the first function took as an input?

The error given in this case is

```
src\Test.hs:25:8: error:
    * Could not deduce: r ~ '[Test, Trace, Lift IO]
      from the context: Member Test r
        bound by the type signature for:
                   test :: forall (r :: [(* -> *) -> * -> *]).
                           Member Test r =>
                           Semantic r () -> IO ()
        at src\Test.hs:24:1-47
      `r' is a rigid type variable bound by
        the type signature for:
          test :: forall (r :: [(* -> *) -> * -> *]).
                  Member Test r =>
                  Semantic r () -> IO ()
        at src\Test.hs:24:1-47
      Expected type: Semantic r () -> IO ()
        Actual type: Semantic '[Test, Trace, Lift IO] () -> IO ()
    * In the expression: runM . runTraceIO . runTestIO
      In an equation for `test': test = runM . runTraceIO . runTestIO
    * Relevant bindings include
        test :: Semantic r () -> IO () (bound at src\Test.hs:25:1)
```

**Comment by jhenahan** [comment]
The error for `testToIO` is telling you that the inferred type is `Semantic '[Test, Trace, Lift IO] () -> IO ()`. That is, you have exactly a `Test`, `Trace`, and `Lift IO` effect. Your type says that you may have some other ones, but there's no information about what those might be, nor are they handled by the function. Changing the type signature will make it typecheck.

`test1` strips a `Test` effect off, `test2` strips a `Trace` effect off. Finally, you're left with a `'Semantic [Lift IO] ()`, which is handled by `runM`.

```

**Comment by sandoichi** [comment]
But the problem is that the `Semantic r a` that `test1` takes only has a `Test` effect on the `r` coming into it. The `Trace` and `Lift IO` get **added** by the interpreter `runTestIO`

So isn't this
```haskell
test2 . test1 :: Member (Lift IO) r => Semantic (Test ': Trace ': r) a -> Semantic r a
```
Saying that the expected input is a `Semantic` that **already has Test AND Trace on it**? That isn't true because the original input does not have `Trace` (because it only gets trace as a result of `runTestIO` on it).

Also, it makes sense that `Member Test r` means that `Test` is just one of many possible effects that could be there. But this is what @isovector mentioned that I should be using, right? At some point, doesn't something has to figure out what the total list of effects are inside of `r` to know that we can `runM` on it when only `Lift IO` is left. 

Being that different interpreters could be adding effects, not just removing them (like in my case), I'm not sure how this would work.

**Comment by sandoichi** [comment]
I've created some more tests and have been successful only if I restrict the input using `'[Test]` and using `reinterpret2` instead of `interpret`, effectively removing any use of `Member`

```haskell
runTest :: Member (Lift IO) r
           => Member Trace r
           => Semantic (Test ': r) a
           -> Semantic r a
runTest =
  interpret $ \case
    DoTest -> do
      trace $ "This is a test"
      sendM $ copyFile "C:\\test.txt" "D:\\test.txt"

runTest2 :: Semantic '[Test] a
            -> Semantic '[Trace, Lift IO] a
runTest2 =
  reinterpret2 $ \case
    DoTest -> do
      trace $ "This is a test"
      sendM $ copyFile "C:\\test.txt" "D:\\test.txt"

runTest3 :: Semantic (Test ': r) a
            -> Semantic (Trace ': Lift IO ': r) a
runTest3 =
  reinterpret2 $ \case
    DoTest -> do
      trace $ "This is a test"
      sendM $ copyFile "C:\\test.txt" "D:\\test.txt"


-- fail
--test :: Member Test r => Semantic r a -> IO a
--test = runM . runTraceIO . runTest

test2 :: Semantic '[Test] a -> IO a
test2 = runM . runTraceIO . runTest2

test3 :: Semantic '[Test] a -> IO a
test3 = runM . runTraceIO . runTest3

-- fail
--test4 :: Semantic '[Test] a -> IO a
--test4 = runM . runTraceIO . runTest
```

**Comment by jhenahan** [comment]
If I understand the `Semantic` machinery correctly (spoiler: I probably don't), I think you may just be intuiting things backwards (or sideways?).

`runTestIO` (`test1`) and `runTraceIO` (`test2`) aren't _adding_ effects, they're describing the effects that you're admitting in the DSL you've constructed.

Example:

Let's define the standard teletype interface.

```haskell
data Console m a where
  ReadLine :: Console m String
  WriteLine  :: String -> Console m ()
  Done :: Console m ()

makeSemantic ''Console

runConsoleIO :: Member (Lift IO) r => Semantic (Console ': r) a -> Semantic r a
runConsoleIO = interpret \case
  ReadLine     -> sendM getLine
  WriteLine msg  -> sendM $ putStrLn msg
  Done -> return ()
```

This gives me a DSL with only three terms: `ReadLine`, `WriteLine`, and `Done`.

I can use this to write my business logic.

consoleWithFunc
  :: (String -> String)
  -> Semantic (Console ': r) ()
  -> Semantic (Console ': r) ()
consoleWithFunc f k = do
  a <- readLine
  when (a == "") done
  when (a /= "") do
    writeLine $ f a
    k

-- Continuations so we can build up chains of behavior
echoK :: Semantic (Console ': r) () -> Semantic (Console ': r) ()
echoK = consoleWithFunc id

revK :: Semantic (Console ': r) () -> Semantic (Console ': r) ()
revK = consoleWithFunc reverse

-- Fixpoints
echo :: Semantic (Console ': r) ()
echo = fix echoK

rev :: Semantic (Console ': r) ()
rev = fix revK

alternating :: Semantic (Console ': r) ()
alternating = fix (echoK . revK)
```

So now I have some programs to run in my DSL.

In order to actually run these programs, I need to specify how to interpret them.

`runConsoleIO` says it can take any `Semantic` with at least `Console` and `Lift IO` effects and interpret my `Console` DSL in `IO`.

```haskell
runConsoleIO alternating :: Member (Lift IO) r => Semantic r ()
```

If I'm happy with that, I can just say

```haskell
runM @IO $ runConsoleIO alternating
```

and I'm done. On the other hand, if I want to allow additional effects in my programs, I need to add interpreters for those effects. Suppose I want someone to be able to write trace statements in programs using the `Console` DSL.

```haskell
runTraceIO . runConsoleIO :: Member (Lift IO) r => Semantic (Console ': Trace ': r) a -> Semantic r a
```

The type says "I will strip off your `Console` and `Trace` effects and leave any others alone". What this means practically is that it is applying semantics to the AST you've constructed with your program. If you never use the `trace` term in your program, this will do no work because it has nothing to work on.

That is, I can say

```haskell
runM @IO . runTraceIO $ runConsoleIO alternating
```

and my existing programs do not change at all. Adding interpreters doesn't _add effects_, but it adds _terms_ to your DSL, and semantics with which to decorate the AST.

The key takeaway is that the type says what effects your programs (in your DSL) _could_ use, not the ones they actually _do_ use.

**Comment by sandoichi** [comment]
Thanks for the detailed response, @jhenahan 

That makes a lot of sense. I'm still trying to figure out though what would happen if say you turned this
```haskell
Done -> return ()
```
into
```haskell
Done -> do
  trace "done"
  return ()
```
From what I've been reading in the docs, it seems like you could take 3 approaches:
```haskell
-- interpret and add Trace member
runConsoleIO :: Member (Lift IO) r => Member Trace r => Semantic (Console ': r) a -> Semantic r a
runConsoleIO = interpret \case
  ReadLine     -> sendM getLine
  WriteLine msg  -> sendM $ putStrLn msg
  Done -> do
    trace "done"
    return ()

-- reinterpret and have Trace show up in the output
runConsoleIO2 :: Member (Lift IO) r => Semantic (Console ': r) a -> Semantic (Trace ': r) a
runConsoleIO2 = reinterpret \case
  ReadLine     -> sendM getLine
  WriteLine msg  -> sendM $ putStrLn msg
  Done -> do
    trace "done"
    return ()

-- reinterpret and run trace to eliminate it
runConsoleIO3 :: Member (Lift IO) r => Semantic (Console ': r) a -> Semantic r a
runConsoleIO3 = runTraceIO . reinterpret \case
  ReadLine     -> sendM getLine
  WriteLine msg  -> sendM $ putStrLn msg
  Done -> do
    trace "done"
    return ()
```
This is what I meant by "adding effects in the interpreter" since even though it is stripping out `Console` from `r`, it is introducing `Trace`

I'm not sure what the difference is between example 1 and 2 in (adding `Member Trace r` compared to `(Trace ': r)`, but I've been finding that having new effects show up in the output of my run functions makes it tough to completely run it down to IO. 

For example, in the program I'm trying to write, I have 5 effects that I need to run. All 5 can produce an `Error` during run, some do `Trace` during run. I've tried to simply chain together the running of them like `runM . runError . runTrace . runE3 . runE2 . runE1` but since `runE1` _introduces_ `Trace` and `Error` in it's semantic output, I get errors saying things like `Expected E2 but got Error/Trace`

I don't know which of these 3 approaches is the most practical. It seems like running every new effect that got introduced will at least allow me to compile, but I'm not sure if that is an antipattern here (I would prefer to handle my `Error` effects at a different layer of my program,  rather than within each `runE` function)...

**Comment by jhenahan** [comment]
So, if my intuition about decorating an AST is correct, I don't think it should be an anti-pattern to run whatever interpreters you need to give semantics to each term.

The way I look at it (which, again, may be wrong), is that once you've written a program in your DSL, what you're really looking at is an AST with no semantics.

If you introduce `trace` or whatever else into that tree, you need to give that term a meaning.

In your `runConsoleIO` and `runConsoleIO2`, that happens outside the interpreter, so you get to pick when you apply the `Trace` interpreter (sort of, see below), but you _have_ to apply it at some point. This is good for when, say, you want to trace to a log file rather than to your terminal.

While your `runConsoleIO` and `runConsoleIO2` look very similar, I _think_ they say subtly different things. Specifically, in the first you're saying that the `Trace` has to be dealt with _eventually_, but in the second you're saying that `Trace` must be dealt with _immediately_. In the last one, you're dealing with it yourself, immediately.

E.g.:

I can write

```haskell
data Nop m a where
  Nop :: Nop m ()

makeSemantic ''Nop

runNopIO :: Member (Lift IO) r => Semantic (Nop ': r) a -> Semantic r a
runNopIO = interpret \case
  Nop -> return ()
```

for a trivial non-tracing effect.

Now I can write (relabeling your `runConsoleIO` as `runConsoleIO1` for clarity):

```haskell
runM @IO . runTraceIO . runNopIO $ runConsoleIO1 alternating -- AOK, the Trace gets dealt with at some point
runM @IO . runTraceIO . runNopIO $ runConsoleIO2 alternating -- Not OK, the Trace *must* be dealt with next
runM @IO . runTraceIO . runNopIO $ runConsoleIO3 alternating -- AOK, the Trace was already dealt with
```

**Comment by sandoichi** [comment]
So I think that when you said 
> ...in the first you're saying that the Trace has to be dealt with eventually, but in the second you're saying that Trace must be dealt with immediately

it all started to click for me! I've since been able to restructure my interpreters to handle certain effects immediately within the interpreters themselves, and represent others as `Member`s of the output. I also had to start using `@`s in a couple of places when running the interpreters (namely `runError` and `runM`) and that took care of a lot of ambiguity errors that I had. 

This restructuring has allowed me to not have to bubble up certain effects in my `runE` output that I'm going to always handle the same, simple way (`runTraceIO` for example), and only have to expose something that I want to handle in a special way elsewhere (`Error`).

I wonder under what circumstances you would want to use `reinterpret` to bubble up the effect and force it to be handled first (like in example `runConsoleIO2` from the previous post). I suppose that would be nice if say you wanted to handle that specific occurrence of the effect differently than another occurrence of it later in your program.

**Comment by jhenahan** [comment]
Glad that helped! Writing all that out helped me crystallize a lot of hazy stuff in my own head, and the fact that it worked out for you makes me think that maybe I grok things a little better than I thought. 😄 

Yeah, I expect you'd be more likely to write something like `runConsoleIO2` in library code than in an application. Like a "bring your own trace interpreter" kind of function. I suppose it would seem less weird for something like `Error`, since layered custom error handlers seem much more likely than layered custom tracers.

**Comment by isovector** [comment]
I love that you two are hashing this out --- it's helpful for me as the library guy to find out where I need to write more documentation.

In particular, I'd like to go on record saying "using `reinterpret` is **wrong** if you don't immediately handle the new effects." Which is to say

```haskell
runConsoleIO2 :: Member (Lift IO) r => Semantic (Console ': r) a -> Semantic (Trace ': r) a
runConsoleIO2 = reinterpret \case
  ReadLine     -> sendM getLine
  WriteLine msg  -> trace msg
```

is bad, but both


```haskell
runConsoleIO2 :: Member (Lift IO) r => Semantic (Console ': r) a -> Semantic r a
runConsoleIO2 = runTraceIO . reinterpret \case
  ReadLine     -> sendM getLine
  WriteLine msg  -> trace msg
```

and 

```haskell
runConsoleIO2 :: (Member (Lift IO) r, Member Trace r) => Semantic (Console ': r) a -> Semantic r a
runConsoleIO2 = interpret \case
  ReadLine     -> sendM getLine
  WriteLine msg  -> trace msg
```

are fine

**Comment by isovector** [comment]
Are your questions adequately answered, @sandoichi ?

**Comment by sandoichi** [comment]
@isovector yep! I've been using polysemy daily and haven't hit any more walls of confusion yet (though that will probably change when I attempt to use Tactics in the future :) ). Thanks again

**Comment by isovector** [comment]
That brings joy to my heart! 

If you have some time, maybe take [`polysemy-plugin`](https://hackage.haskell.org/package/polysemy-plugin) out for a spin; it should dramatically improve the type inference when using effects --- no more type applications in most cases!
