### ISSUE TITLE
Interpreter Zoo

### ISSUE THREAD

**Issue by jhenahan** [isovector/polysemy#20]
As I've been thinking about common effects and compatibility with existing libraries, I started thinking about an interpreter zoo.

The main thing that comes to mind is the pile of logging abstractions and exception handlers floating around Hackage.

It makes some kind of sense for common effects (`Input`, `Output`, `State`, etc.) to live in the `polysemy` "core" since they can be defined without any dependencies, but interpreters potentially require arbitrary dependencies. If there's an identifiable common API between these log libraries, for instance, the effect could be written once in `polysemy`, then a user could use `polysemy-co-log` or `polysemy-monad-logger` or whatever rather than writing their own interpreters.

To this end, it'd be interesting to work on an ecosystem of interpreters for a variety of primitive effects. Mainly because there are some non-trivial optimizations that need to happen (late specialization, INLINE pragmas, your compiler plugin, etc.) to make things really fast, and paying that cost the minimum number of times would be nice.

Is this sensible? Or is the vision for the library that it ought to be easy enough to write these interpreters that having "blessed" configurations would be unnecessary? On the other hand, are interpreters so application-specific as to make sharing them sort of pointless?

**Comment by isovector** [comment]
My dream is to turn all "implementation details" into library code, which only works if there's a library to put them in!

I agree with trying to keep the core library as lightweight as possible. To that end I've been thinking about a `polysemy-contrib` where users can open PRs for any effects/interpreters they write and find useful. Clearly beneficial ones should eventually end up in `polysemy` proper. Common dependencies (`bytestring`, `text`, `transformers`, `lens`, etc) would be fine to pull into `polysemy-contrib`, but I'd prefer to keep it away from dependencies we wouldn't expect people to already have in their project.

In addition, I'm ok with writing lots of similar-feeling effects, eg `Input`/`Reader`, `Trace`/`Output`/`Writer`, so long as we choose one to be the "official" effect, and provide interpretations to/from the official one. c.f. `runTraceAsOutput`.

More exotic dependencies can indeed live in their own packages, `polysemy-co-log` or something.

The `Random` effect is a good example of something that should probably live in `polysemy-contrib` as a starting point.

If this makes sense to you, I'd love any help I can get in making it a reality!

**Comment by isovector** [comment]
Along those lines, here are a list of some interpreters I think should exist in `polysemy` but I haven't gotten around to writing yet:

```haskell
type InterpreterOf e r = forall x. Semantic (e ': r) x -> Semantic r x
type ReinterpretationOf e e' r = forall x. Semantic (e ': r) x -> Semantic (e' : r) x

runStateInIO :: Member (Lift IO) r => MVar s -> InterpreterOf (State s) r
runBatchOutput :: Int -> ReinterpretationOf (Output w) (Output [w]) r
runTraceOutput :: (Member Trace r, Show w) => InterpreterOf r (Output w)

data KVStore k v m a where
  GetKV :: k -> KVStore k v m (Maybe v)
  PutKV :: k -> v -> KVStore k v m ()

runKVStorePurely :: Map k v -> Semantic (KVStore k v ': r) a -> Semantic r (Map k v, a)
```

**Comment by adamConnerSax** [comment]
On the contrib side, are you interested in a random-fu effect?  I've got a version of that.  Should there be multiple random effects or should they somehow have the same interface and there be different interpretations?  That question exists in the logging space as well.

If you collect them, it's be good to have some coding guidelines, as well as some---hmm--philosophical (?) ones about what sorts of interpreters to include or not and whether to provide the convenience of (mtl) compatibility where possible with instances of constraints.

Anyway, I'd be pleased to see this happen and happy to contribute.  I've got the random-fu thing.  Also a log thing that probably doesn't belong until I re-write it in terms of your output stuff.

**Comment by isovector** [comment]
I'm absolutely interested! I'd prefer for only one `Random` effect, with interpreters to transform between them, but I wouldn't fight for it if it doesn't seem worthwhile.

Coding guidelines and philosophy are a good idea; @pkinsky, @cassiebaer, @runarorama, @Voltir, @tathougies --- IIRC, we used to have some documentation on this at Takt. Do you recall what our guidelines behind writing new effects and interpreters was?

**Comment by isovector** [comment]
I guess the next actions here are for me to write up these guidelines!

**Comment by adamConnerSax** [comment]
You could also start a library, structured how you like and then I'd be happy to add a PR for random-fu and then you can decide what you don't like about that and guidelines might evolve from that? Either way.  I'm happy to wait until some exist also.
I don't think it'd be so easy to make one effect two interpretations without taking a pretty strong stand on how randomness ought to work.  The "primitives", are quite different. Maybe they are isomorphic in a way I don't see but, well, I don't see it. 
Also, maybe it's better to let the zoo be a little zoo-ish?  And then occasionally use acquired clarity about what is good and useful or what can be generalized or whatever to promote things to the core lib?

**Comment by isovector** [comment]
Welcome to the zoo: https://github.com/isovector/polysemy-zoo/
