### ISSUE TITLE
Overlapping instances?

### ISSUE THREAD

**Issue by adamConnerSax** [isovector/polysemy#21]
Hmm.  Trying to write slightly more general interpreters for running things that might be sitting "on top of" other monads where all we have are constraints for them.  Should that work?  I am getting 
```
 • Overlapping instances for Polysemy.Internal.Union.Find
                                  '[P.Lift IO, P.Lift m] (P.Lift m)
        arising from a use of ‘KPM.runPandoc’
      Matching instances:
        instance forall k (z :: [k]) (t :: k) (_1 :: k).
                 (Polysemy.Internal.Union.Find z t,
                  Polysemy.Internal.Union.Found (_1 : z) t
                  ~ 'Polysemy.Internal.Union.S
                      (Polysemy.Internal.Union.Found z t)) =>
                 Polysemy.Internal.Union.Find (_1 : z) t
          -- Defined in ‘Polysemy.Internal.Union’
        instance [overlapping] forall k (t :: k) (z :: [k]).
                               Polysemy.Internal.Union.Find (t : z) t
          -- Defined in ‘Polysemy.Internal.Union’
      (The choice depends on the instantiation of ‘m’
       To pick the first instance above, use IncoherentInstances
       when compiling the other instance declarations)
    • In the expression: KPM.runPandoc @m
      In an equation for ‘runPandoc’: runPandoc = KPM.runPandoc @m
      In the expression:
        do let runPandoc ::
                 forall a.
                 Semantic '[Pandoc,
                            KLog.Logger KLog.LogEntry,
                            KLog.PrefixLog,
                            PE.Error KPM.PandocError,
                            P.Lift IO,
                            P.Lift m] a
                 -> Semantic '[KLog.Logger KLog.LogEntry,
                               KLog.PrefixLog,
                               PE.Error KPM.PandocError,
                               P.Lift IO,
                               P.Lift m] a
               runPandoc = KPM.runPandoc @m
...
```

**Comment by isovector** [comment]
Can you share all the code?

**Comment by adamConnerSax** [comment]
Yes, but it's..a lot. 
For now, I retreated to specifying ```PandocIO``` as ```m```.  Once that works, I'll go back and re-create, check in a branch with the error and point you to that, okay?   But it might not be for a bit...
Thanks for trying to help!

**Comment by adamConnerSax** [comment]
Okay.  Here's the code which won't compile (the master branch has the same thing with PandocIO specified and one more run function to run PandocIO, which maybe makes the difference?):
https://github.com/adamConnerSax/knit-haskell/blob/OverlappingInstances/src/Knit/Report.hs#L145

```
src/Knit/Report.hs:145:7-22: error:
    • Overlapping instances for Polysemy.Internal.Union.Find
                                  '[P.Lift IO, P.Lift m] (P.Lift m)
        arising from a use of ‘KPM.runPandoc’
      Matching instances:
        instance forall k (z :: [k]) (t :: k) (_1 :: k).
                 (Polysemy.Internal.Union.Find z t,
                  Polysemy.Internal.Union.Found (_1 : z) t
                  ~ 'Polysemy.Internal.Union.S
                      (Polysemy.Internal.Union.Found z t)) =>
                 Polysemy.Internal.Union.Find (_1 : z) t
          -- Defined in ‘Polysemy.Internal.Union’
        instance [overlapping] forall k (t :: k) (z :: [k]).
                               Polysemy.Internal.Union.Find (t : z) t
          -- Defined in ‘Polysemy.Internal.Union’
      (The choice depends on the instantiation of ‘m’
       To pick the first instance above, use IncoherentInstances
       when compiling the other instance declarations)
    • In the first argument of ‘(.)’, namely ‘KPM.runPandoc @m’
      In the second argument of ‘(.)’, namely
        ‘KPM.runPandoc @m
           . maybe id wrapPrefix loggingPrefixM
               . KD.toNamedDocListWithM
                   (fmap BH.renderHtml . KO.toBlazeDocument writeConfig)’
      In the second argument of ‘(.)’, namely
        ‘filteredLogEntriesToIO ls
           . KPM.runPandoc @m
               . maybe id wrapPrefix loggingPrefixM
                   . KD.toNamedDocListWithM
                       (fmap BH.renderHtml . KO.toBlazeDocument writeConfig)’
    |
145 |     . KPM.runPandoc @m -- PA.PandocIO
    |       ^^^^^^^^^^^^^^^^
```

Thanks for looking!  I've got no idea how to think about that error.

**Comment by jhenahan** [comment]
This looks odd to me:

``haskell
type KnitEffectsMany m =
  '[ KD.Docs KP.PandocWithRequirements
   , KPM.Pandoc
   , KLog.Logger KLog.LogEntry
   , KLog.PrefixLog
   , PE.Error PA.PandocError
   , P.Lift IO
   , P.Lift m
   ]

type KnitEffectsManyC m = (P.Member (P.Lift m) (KnitEffectsMany m))
```
`KnitEffectsManyC m` says that `P.Lift m` is a `Member` of `KnitEffectsMany m`, but `P.Lift m` is already explicitly in `KnitEffectsMany m`. Was that necessary to get things to type check?

**Comment by isovector** [comment]
Yeah, something definitely weird is going on here. For example, you have a function which takes a `forall a . P.Semantic r a -> P.Semantic (KnitEffectsMany m) a`... and then just runs it. Why not just ask callers of your function to call that first?

Furthermore, as @jhenahan points out, 

```haskell
type KnitEffectsOne m =
  '[ KP.ToPandoc
   , KPM.Pandoc
   , KLog.Logger KLog.LogEntry
   , KLog.PrefixLog
   , PE.Error PA.PandocError
   , P.Lift IO
   , P.Lift m
   ]

type KnitEffectsOneC m = (P.Member (P.Lift m) (KnitEffectsMany m))
```

this thing is wild. I think maybe what you want is to turn on `ConstraintKinds` and:

```haskell
type KnitEffectsOne m r =
   ( Member (KP.ToPandoc) r
   , Member (KPM.Pandoc) r
   , Member (KLog.Logger KLog.LogEntry) r
   , Member (KLog.PrefixLog) r
   , Member (PE.Error PA.PandocError) r
   , Member (P.Lift IO) r
   , Member (P.Lift m) r
   )

then use this: `KnitEffectsOne m r => Semantic r ...`
```

**Comment by adamConnerSax** [comment]
@jhenahan:  Yes!  It's weird.  But without it I get:
```
src/Knit/Report.hs:145:7: error:
    • Ambiguous use of effect 'P.Lift'
      Possible fix:
        add (Member (P.Lift m) '[KLog.Logger KLog.LogEntry,
                                 KLog.PrefixLog, PE.Error KPM.PandocError, P.Lift IO,
                                 P.Lift m]) to the context of 
          the type signature
      If you already have the constraint you want, instead
        add a type application to specify
          'm' directly
    • In the first argument of ‘(.)’, namely ‘KPM.runPandoc @m’
      In the second argument of ‘(.)’, namely
        ‘KPM.runPandoc @m
           . maybe id wrapPrefix loggingPrefixM
               . KD.toNamedDocListWithM
                   (fmap BH.renderHtml . KO.toBlazeDocument writeConfig)’
      In the second argument of ‘(.)’, namely
        ‘filteredLogEntriesToIO ls
           . KPM.runPandoc @m
               . maybe id wrapPrefix loggingPrefixM
                   . KD.toNamedDocListWithM
                       (fmap BH.renderHtml . KO.toBlazeDocument writeConfig)’
    |
145 |     . KPM.runPandoc @m -- PA.PandocIO
    |       ^^^^^^^^^^^^^^^^
```

I actually get that (Ambiguous use of P.Lift...) a lot, even when I have the constraint and the type application, which makes me think I am doing something wrong only I can't spot what it is.

@isovector You're right about the ```runOthers``` function.  I'm trying to make a function that is kind of "one-stop-shopping" for running this set of effects.  I'm imagining a user who uses this set of features and doesn't want to know more than they have to about how polysemy works.  So they might want to run it on top of another monad. But also have other effects, like randomness, that this function doesn't handle.  But you're right, I don't add much value by just running a function they have to provide.  So I dropped it.
I tried your constraint--it would be cool if that worked!  I thought you might have to specify an order to actually run things--but then I get ```Ambiguous use of effect 'P.Lift'``` at both places where I type-apply ```m``` and I don't know why.
I've checked that version in now, in case it's of interest.
Thanks!

**Comment by jhenahan** [comment]
Okay, so looking at what your code is actually doing (at least at a high level), here's what I think is going on.

`knitHtmls` interprets the effects listed in `KnitEffectsMany` (a whole bunch of them!). The way I intuitively think of the "visible" part of interpretation is that you're stripping an effect off the top of `r`. So the issue, I think, is that your type says "I take a `Semantic` with some arbitrary effect stack (that I can't look at, because `forall r`), and I also handle interpretation of all of these other effects". But then the constraint on that type says that you have an unhandled `KnitEffectsMany` (that is, a stack of unhandled effects) in that `r` you can't look at. But that's not really what you want to say, I don't think.

Really, for any interpreter on which you can `runM` and get a result out, all you can have left is a `Semantic '[Lift m] a`, which I think is what you have. The interpreter obligations for `KnitEffectsMany` are entirely discharged by your chain of interpreters.

To that end, I think your actual type looks more like

```haskell
knitHtmls
  :: ( PA.PandocMonad m
     , MonadIO m
     , MonadError PA.PandocError m
     )
  => Maybe T.Text -- ^ outer logging prefix
  -> [KLog.LogSeverity] -- ^ what to output in log
  -> PandocWriterConfig -- ^ configuration for the Pandoc Html Writer
  -> P.Semantic r () -- ^ Knit effects "over" m
  -> m [KP.NamedDoc TL.Text] -- ^  named documents, converted to Html as Text.
```

(I didn't check if that typechecks, so it's more of a feely guess)

I think that'd also let you strip out the `@m`s.

You still don't know anything about `r`, but the interpreters that your user chains in here would admit additional effects (though I don't really know what happens if they use their own interpretation of one of the effects you handle). I think this feels weird because this interpreter doesn't _compose with_ so much as it _consumes_ another interpreter, which seems odd.

If the interpreter is built with `reinterpret` (and so handles its own effects), your type doesn't change, so that'd be fine. But if you want to allow some arbitrary interpreter, then you're going to run into the issue of people interpreting _your_ effects some other way, and I have no idea how to write a constraint for "might have any effect at all". On the other hand, this does let you say explicitly what the chained interpreter can do, by expressing `Member SomeEffect r` for the `r` in that `Semantic r ()`.

**Comment by adamConnerSax** [comment]
Hmm. I don’t get how that can work without constraints on r that allow all the interpreters to be run. They each have constraints and/or types that indicate specific effects being in r. But maybe that’s what you’re saying at the end?

But I think I’m being dumb. If I know (MonadIO m), I can just run my (working!) version using PandocIO giving something in IO and then use liftIO to get to m. So what I though was a requirement for running this set of effects in a larger environment isn’t one, right?

I think I got lost trying to be general instead of trying to have the function do what it says, use a specific set of effects to create a set of html docs (in IO, since Pandoc requires that bit).

I’ll close this soon, I’m away from a laptop for a bit...

Anyway, thanks for all the help! I definitely still don’t quite get what’s happening but I’m pretty sure this doesn’t need to work in this complicated way.

Thanks!

Adam

**Comment by adamConnerSax** [comment]
Okay, maybe I was 0.5 dumb. liftIO solves part of my problem but I’d still prefer a version of the original idea to work so that the thing knitHtmls is called on can have access to m. I’ll keep fiddling...

**Comment by adamConnerSax** [comment]
Having had more time to think, and you all to point out what’s weird, I think I can ask this more clearly. What I want is something that acts like a 
```SemT r m``` with 
```Haskell
runSemT :: Member (Lift m) r => (forall x. Sem r x -> Sem ‘[Lift m] x) -> SemT r m x -> m x
runSemT consume = runM . consume
```
where that run interprets/consumes all the effects in ```r``` *and* can use ```m``` to do it. 
I’m happy to abandon the mtl-style stuff but I’m trying to figure out how to interoperate with it most smoothly.
That is, I’m trying to figure a way that a function using the polysemy effects can also access effects in another monad, at least some of them...
Does that make sense?

**Comment by isovector** [comment]
`SemT r m` is indistinguishable from `Sem r` -- it's just a `Member (Lift m) r` constraint.

You can also double down on constraints for those things:

```haskell
-- MonadResource is from the `resourcet` package
foo :: forall m r. (Member (Lift m) r, MonadResource m) => Semantic r ReleaseKey
foo = do
  (key, ()) <- sendM $ allocate @m (putStrLn "hello") (const $ putStrLn "goodbye")
  pure key
```

**Comment by adamConnerSax** [comment]
Hmm.  Maybe I need a simpler question answered:
Given that I have a ```Member (Lift m) r``` constraint and that I have type-applied @m on the line in question, what is the "Ambiguous use of effect 'P.Lift'..." message telling me? 
I'd like to chase it down and fix it or understand why it's impossible. 
I know that maybe I'm doing something silly or impossible but I don't yet get why. I'm just trying to run all the effects in a stack with ```Lift m``` at the bottom and be left with ```m a``` which seems like it ought to be easy.  The only wrinkles here are the use of ```m``` in the interpreter.  But as you point out, that shouldn't be a problem.  So what is going wrong?

**Comment by isovector** [comment]
Sorry, I'm definitely bogged down in the details here. That being said, I'm 65% sure the issue comes from explicitly having `KnitEffectStack` rather than allowing the polymorphism to do what it's supposed to.

Try disabling custom errors in `polysemy` via adding this to your `stack.yaml`:

```yaml
flags:
  polysemy:
    custom-errors: false
```

and see if that gives a more helpful error message for your ambiguous lift.

**Comment by adamConnerSax** [comment]
Don't be sorry!  I so appreciate all the help.

I got the explicit HList version to work.  I had defined ```LastMember``` wrong.  But I know it feels like a code-smell that I need it, or the explicit HList version at all.

Code is [here](https://github.com/adamConnerSax/knit-haskell/blob/OverlappingInstances/src/Knit/Report.hs#L124) if you are interested.  [Example use](https://github.com/adamConnerSax/knit-haskell/blob/OverlappingInstances/examples/ExampleDoc1.hs#L29)

Things can be inferred at use-sites so it's not so bad that the interpreter needs the list to be explicit, maybe?

When I try the polymorphic version of ```consumeKnitEffectStack``` I get (without the "error-messages" flag) a "Could not deduce r ~ XXX" where XXX is the stack I was using explicitly in the monomorphic version. So that seems to push back towards the explicit HLIst version.

I am planning to remove PandocIO from this all-together pretty soon since it's just a combination of MonadError, IO and some MonadRandom.  So I will interpret it all via those.  And then maybe this will be simpler and I can figure out how to get the polymorphic version to work...Until then, should I close this?

In general, should type inference be powerful enough to figure out the HList required for a set of effects to be interpreted/consumed? If so, something in one of my interpreters must break this, requiring more ordering information or something.  It would be good to know where that breaks down here...

**Comment by jhenahan** [comment]
I guess the thing I'm failing to grasp is why you need to have the explicit `KnitEffectsStack`. As I understand it, your `r` is polymorphic (i.e., the order of effects is not fixed) until you start consuming the effects. Your `KnitEffectsStack` seems to impose an ordering on `r`, which feels like it's working against the library rather than with it.

**Comment by adamConnerSax** [comment]
Right!  I would also rather not have it be explicit.  So your question confuses me.  My best guess is that you could be asking one of two things:
1.  Why, in these "knit" functions, am I using an explicit HList instead of a polymorphic ```r```?  The answer there is that I would if I could!  But when I try I get, depending on the use of custom-errors, a failure to deduce the exact stack or an ambiguous use of ```Lift m```.  My rough understanding of this is that my series of interpreters require ```Member (Lift m) r``` in a few different stacks, as each effect is run/interpreted.
2.  But maybe you are asking why I want to run/interpret these effects over an arbitrary Monad ```m```?  That's because I am imagining a use-case where someone has an existing monad stack and wants to use my library to create Html reports while working in that stack.  And they might want to use their monad to, e.g., make DB calls, while building the document.  That is, I am trying to make this flexible and usable by someone who isn't interested in replacing their entire stack with polysemy but wants to use this package to create Html reports this way.
@jhenahan Does that make sense?

**Comment by adamConnerSax** [comment]
It might be clearer with an example.  If you have a chance, take a look at:
https://github.com/adamConnerSax/knit-haskell/blob/master/examples/MtlExample.hs
That shows use of the polysemy stack being run (via ```knitHtml```) "over" an mtl stack in a case where ```liftIO``` wouldn't be sufficient because the function that uses the polysemy effects also uses effects from that base monad. 
I want this to work (which it does now! But using an explicit stack and that ```LastMember``` thing in the intepreter...) for any user who wants to be able to use this functionality without converting an existing app to use polysemy.

**Comment by jhenahan** [comment]
I'll dig around this week/end and see if I can figure something out, assuming the author doesn't beat me to it. :smile:

**Comment by isovector** [comment]
I also want this to work! Is there any chance I can persuade you into putting together a single-file simplification of your code, which only has `polysemy`/`base`/`containers`/`transformers`/`mtl` as dependencies? I'm sure this would be easy to track down if I could see the exact errors in context.

Alternatively we could set up a call and pair on it if you'd like!

**Comment by adamConnerSax** [comment]
Thank you both so much for being so helpful! This particular thing has gotten simpler as I've worked on it and I am down to just the polymorphic vs. explicit type-level-list of effects.
( I re-implemented the ```PandocIO``` monad just using ```IO```--because it seemed very annoying to ask users to put ```PandocIO``` at the bottom of their stacks!--and the the necessity of the ```LastMember``` thing went away. Not sure why...)

I'm happy to try and replicate it in a simpler context.  But let me summarize where I am and what questions remain just to be sure it's worth solving and I know what I'm trying to replicate! 

1. I have successfully written an (interpreter?  run-function? effect-consumer?) which:
  a. Consumes a fixed set of effects, some of which require IO. 
  b. Returns a base monad (non-polysemy), via runM, said monad having a ```MonadIO``` instance.
  c. Allows the effectful thing being "run" to access the base monad via the standard mechanism of using ```sendM``` (and the presence of ```Lift m``` in the TLL).
2. Said interpreter requires, at least in my version, a fixed type-level-list (TLL) of effects (rather than a polymorphic TLL and constraints) in it's signature.
If I try to use a polymorphic TLL and constraints I get a "could not deduce r ~ XXX..." error, where XXX is exactly the stack I specify in the working version.
3.  I can run this interpreter on effectful things that *are* specified polymorphically, as demonstrated in the [example](https://github.com/adamConnerSax/knit-haskell/blob/master/examples/MtlExample.hs#L45) linked in my last post.  

So, on the one hand, I'm not sure there's still a problem.  I have bent it, more or less, to my grasping and ineffectual will.  But if it still seems to you both that I ought to be able to write [this](https://github.com/adamConnerSax/knit-haskell/blob/master/src/Knit/Report.hs#L191) interpreter with a polymorphic type in the signature--though it can only possibly work if that type is inferred to be the precise stack I now have to specify! Which I think is why the polymorphic version fails: the function isn't really polymorphic.--then I can try to replicate the issue.  Which is just a question of what circumstances require explicit TLL's vs. polymorphic + constraints.

Also, the ```LastMember``` thing.  That went away but I'm not really sure why.  So I'm not sure I can reproduce the circumstances that require it!  It likely has something to do with running multiple single-effect interpreters some of which use ```sendM``` to use the base monad.  But why that's become simpler when it's ```MonadIO m``` rather than ```(MonadIO m, PandocMonad m)```, I'm not sure.  It also could be a difference between the Pandoc effects [interpreter](https://github.com/adamConnerSax/knit-haskell/blob/master/src/Knit/Effect/PandocMonad.hs#L249) I used when I was relying on the base monad for Pandoc effects and the [one](https://github.com/adamConnerSax/knit-haskell/blob/master/src/Knit/Effect/PandocMonad.hs#L212) I wrote as a re-implementation of that in IO.

**Comment by isovector** [comment]
Ahh, thanks for spelling that out. That makes a lot of sense to me! The reason you have a monomorphic type is because really and truly you have a set of interpreters you want to run _in that order._ In that case, I agree that you need the concrete type.

I'm also happy that whatever changes you've made have alleviated the need for `LastMember`! That thing always struck me as a wart in `freer-simple`. 

If you're happy with the state of things, I'm also happy! It seems like there could be some work done on the library side to improve the ergonomics of typing explicit interpreter compositions, but besides that I'm not sure! Any suggestions for what else this bug has to offer, or is it OK to close?

**Comment by adamConnerSax** [comment]
I'm content to close this and I'l keep an eye out to see if I can understand why that ```LastMember``` thing happened.

Thanks again for all the help!
