### ISSUE TITLE
Investigate removing QuantifiedConstraints

### ISSUE THREAD

**Issue by isovector** [isovector/polysemy#29]
They're used in `Effect` right now, but I'm pretty sure they're not necessary. If they can be removed, we can target older GHC versions.

**Comment by patrickt** [comment]
It’s pretty straightforward to work around the lack of QC’s: you just need to define a dummy `fmap’` defaulting to `fmap`, and use `fmap’` in conjunction with `hoist`. [This](https://github.com/fused-effects/fused-effects/blob/master/src/Control/Effect/Carrier.hs#L16) is what we did in FE.

**Comment by isovector** [comment]
Closed by #38
