### ISSUE TITLE
PVP question

### ISSUE THREAD

**Issue by adamConnerSax** [isovector/polysemy#33]
Water under the bridge now, but was removing the export of "Typeable" consistent with only bumping from 0.1.1.0 to 0.1.2.0?  

I ask because I'm always assuming that I can safely upper bound things at  < A.(B+1).0.0, but in this case that broke because I was using the Polysemy export of ```Typeable``` to add it.  The *constraint* is harmless now that it's not needed, so removing it is backward-compatible, but now my code fails to compile because ```Typeable``` is no longer exported for me to use.

**Comment by mitchellwrosen** [comment]
Removing any exported symbol (even a re-exported one) should be accompanied by a major version bump - it falls under point `1` here: https://pvp.haskell.org/

**Comment by isovector** [comment]
Whoops! Thanks for the heads up. I'm a shit maintainer, so thanks for calling these things out.

Is there any tooling I can use to help with this in the future?

**Comment by mitchellwrosen** [comment]
I'm not sure. I've seen https://hackage.haskell.org/package/hackage-diff but it's old, crufty, and I'm unsure if you can run it on unreleased code.

**Comment by adamConnerSax** [comment]
Did ```Semantic``` become a type synonym in 0.1.2?  That also broke some things.  I would've needed to add 
```{-# TypeSynonymInstances #-}``` for that ```MonadRandom``` instance, though now I'l just update it all to ```Sem```.
I wonder if you can fix that by adding ```TypeSynonymInstances``` to the cabal/package.yaml when making this sort of change?  Otherwise making something a synonym by way of deprecation will always be a breaking change.

**Comment by isovector** [comment]
Yeah, it did become a type synonym. Sorry for the growing pangs here!

Adding `TypeSynonymInstances` to `polysemy` wouldn't help here; it needs to be enabled in _your_ package where you define the instance.

**Comment by adamConnerSax** [comment]
Ah, right.  Was just hoping for the future.  I guess you could rename and make the *new* one a type-synonym?  Then the type synonym thing itself wouldn't be a breaking change?

**Comment by isovector** [comment]
That's a good plan, then for the major version release just swizzle which one is a synonym. I'll keep this in mind!

If you're keen, I'd be very interested in a PR for a checklist of things I should keep in mind before cutting a new release :)

**Comment by adamConnerSax** [comment]
Well, I'd like to help (see my PR in the zoo!) but I've got less experience doing this than you do so I don't think I can be useful in that regard.  I only noticed because I did the cabal update because I needed the plugin (for the zoo) and then my "knit-haskell" package broke because of the ```Typeable``` thing.  But there must be some good resources.
One thought though:  Is there much downside to liberally choosing to bump B (of A.B.C.D) until things are pretty stable?  I guess it will cause people to miss the upgrades but maybe that's the point until things settle down?  Then you could worry less...

**Comment by isovector** [comment]
Sounds like a good plan. I'll do that from now on!
