### ISSUE TITLE
Reimplement `runState` in terms of `hoistStateIntoStateT`

### ISSUE THREAD

**Issue by isovector** [isovector/polysemy#34]
Then we can get rid of the `interpretInStateT`, and `stateful` and friends --- a nice simplification of `Polysemy.Internal.Combinators`

This should be pretty easy: `runState s = flip S.runStateT s . hoistStateIntoStateT`, and then eliminate dead code from there.

**Comment by googleson78** [comment]
Changing `runState` to be 
```runState s = fmap swap . flip S.runStateT s . hoistStateIntoStateT```
results in a failure in `"Union proofs should simplify"` : [error](https://gist.github.com/googleson78/434d70bbe62b666019245755382e7d15).

Also slightly off-topic but: Won't this make eventual removal of dependence on `mtl` more difficult?

**Comment by jhenahan** [comment]
`runStateT` in `mtl` is just a re-export from `transformers`, AFAIK.

**Comment by isovector** [comment]
@googleson78 dang, I was hoping this would be super easy. I'm traveling for the next few weeks, but would love to take a look at this together when I'm home!

**Comment by adamConnerSax** [comment]
A question, slightly off-topic maybe.
I feel like there is something similar about this hoist function and the MonadRandom thing we have been talking about [over in polysemy-zoo](https://github.com/isovector/polysemy-zoo/pull/3).
All of them are ways of trying to accommodate a different version of an effect that polysemy supports.
So, two questions:
-  Maybe these should be in a separate library, polysemy-mtl or polysemy-interop?  That would get rid of the dependencies for users who don't care about mtl.
-  What is the ideal form for such a thing?  I can imagine three versions, though maybe not all would work equally well for all effects.  
1. Something like hoist:  ```hoistX:: Sem (X ': r) a -> XT (Sem r) a```
2. Some kind of orphan instance: ```instance (Member X r) => MonadX (Sem r) where ...```
3. A function--like ```liftIO```---which discharges the constraint within ```Sem ```: ```liftX :: (MonadX m, Member X r) => m a -> Sem r a```.  
I'm not quite sure how that third version would work, but it seems like it keeps most of the convenience of instances without the issue of actually having them.

I'm going to think about how to do that for ```MonadRandom``` in RandomFu.

**Comment by isovector** [comment]
@googleson78 make sure the new `runState` is marked as `INLINE`, also all the functions it calls!

**Comment by googleson78** [comment]
It seems `hoistStateIntoStateT` itself isn't fusing(/doesn't have `SNat` proofs eliminated) properly.
I tried running the proof elimination fusion test using it.

**Comment by isovector** [comment]
Okay, yeah, I see why `hoistStateIntoStateT` wouldn't fuse --- it's not written in the form `Sem $ \k -> m $ \u -> ...`. But unfortunately it can't be, because we don't actually produce a `Sem`! I'm reasonably sure that [!668](https://gitlab.haskell.org/ghc/ghc/merge_requests/668/) will fix this, but until them, we can hold off on this ticket.

**Comment by isovector** [comment]
I don't think this is worth doing.
