### ISSUE TITLE
.@ duplicates effects

### ISSUE THREAD

**Issue by isovector** [isovector/polysemy#42]
Consider the very reasonable effect:

```haskell
data Delayed m a where
  Delay :: Int -> m () -> Delayed m ()
  Cancel :: Delayed m ()


runDelayed
    :: (forall x. r@> x -> IO x)
    -> Delayed :r@> a
    -> IO ~@r@> a
runDelayed lower m = do
  ref <- sendM $ newIORef []
  runDelayed' ref lower m

-- not exported
runDelayed'
    :: IORef ([A.Async ()])
    -> (forall x. r@> x -> IO x)
    -> Delayed :r@> a
    -> IO ~@r@> a
runDelayed' ref lower = interpretH \case
  Cancel -> do
    sendM $ do
      mfuture <- readIORef ref
      for_ mfuture $ \e -> do
        A.cancel e
      modifyIORef ref $ drop 1
    getInitialStateT

  Delay time m -> do
    m' <- runT m
    sendM $ do
      a <- A.async $ do
        threadDelay time
        void $ lower .@ runDelayed' ref $ m'
        modifyIORef ref $ drop 1
      modifyIORef ref $ (++ [a])
    getInitialStateT
```

(that is, it's reasonable besides the fact that it races and should give you back a handle to cancel rather than just canceling whatever it wants.)

Okay, great, but now what happens if you use it like this:

```haskell
runM .@ runDelayed .@ runSomethingElse
```

where `runSomethingElse` needs to lower directly into `IO`?

Well, what happens is that the `newIORef` in `runDelayed` gets duplicated *for each lowering into `IO`.* While that's to be *expected*, but it's certainly not what was *intended*. So that sucks.

Especially because if we generated the `IORef` ourselves in the containing scope, and then called `runDelayed' ref` directly, this function would behave as intended. But no, the hiding of the implementation details in `runDelayed` *explicitly causes bad behavior.*

This is aggressively bad semantics and is in desperate need of a solution.

**Comment by isovector** [comment]
Solution:

Wrap the handlers: `IO (forall x. Sem r x -> IO x)` and add a new `.@`-esque combinator that does the right thing,

**Comment by isovector** [comment]
It's annoying that you can't write `IO (forall x. Sem r x -> IO x)` functions due to the lack of impredicative polymorphism. We'd need to do newtype un/wrapping, which would further complicate the issue.

I wonder if we can get around this by defining the interpreters and combinators in library code with `-XImpredicativeTypes`, and then just not have that in user code? :scream:

**Comment by isovector** [comment]
This works just fine:

```haskell
{-# LANGUAGE ImpredicativeTypes #-}
{-# LANGUAGE RankNTypes         #-}

import Data.Coerce

newtype Id = Id (forall a. a -> a)

foo :: IO (forall a. a -> a)
foo = do
  putStrLn "hello"
  pure $ coerce $ Id id

(.@) :: IO (forall a. a -> a) -> IO (forall a. a -> a) -> IO (forall a. a -> a)
(.@) ibc iab = do
  ab <- iab
  bc <- ibc
  pure $ coerce  $ Id $ \a -> bc $ ab a

main :: IO ()
main = do
  id' <- foo .@ foo
  putStrLn $ id' "world"
```

**Comment by isovector** [comment]
Somebody could put this in the zoo!

**Comment by isovector** [comment]
https://github.com/isovector/polysemy-zoo/commit/7c81b4f8d91cc49dc01e8c2e6301635fb9afc21c

**Comment by googleson78** [comment]
Maybe it's a good idea to put a note/warning on `.@` regarding this?

**Comment by isovector** [comment]
Good idea.
