### ISSUE TITLE
Plugin troubles with HIE

### ISSUE THREAD

**Issue by cah6** [isovector/polysemy#53]
First of all great job on the library, I'm having a great time playing around with it!

My issue now: when using an editor like HIE on VSCode to play with polysemy, it fails to compile in-editor on pieces that require the plugin, I suppose since HIE doesn't get started with the plugin. I tried working around this by putting
`{-# OPTIONS_GHC -fplugin=Polysemy.Plugin #-}` 
at the top of my module but that didn't seem to force it through HIE.

This probably isn't really specific to this plugin, but it would be nice to know if there's a way to force HIE to load a plugin (I tried searching and couldn't find anything) or otherwise get this working. 

Barring that, it might be helpful to provide more examples of helping out the type checker without the plugin? I know I can fix this by writing it "correctly" in the first place, but am having a hard time even figuring that out. For what it's worth, the snippet I'm currently trying to get working without the plugin is
```
deleteKV :: Member (KVStore k v) r => k -> Sem r ()
deleteKV k = updateKV k Nothing
```
from `Polysemy.KVStore` in `polysemy-zoo`.

**Comment by isovector** [comment]
Without the plugin, you'll need to annotate the type of `Nothing`, since GHC is sutpid enough to think that maybe you want _some other_ `KVStore k v'` effect.

As such, try this:

```haskell
deleteKV :: forall k v r. Member (KVStore k v) r => k -> Sem r ()
deleteKV k = updateKV k (Nothing @v)
```

**Comment by isovector** [comment]
As for HIE, I have no idea, sorry! Maybe open a bug with those guys?

**Comment by cah6** [comment]
Yep, will check with them for plugin integration!

That's what I thought was missing, but it's giving the same ambiguity check error with that code above too, exactly as is. Note it gives the same thing if I also remove the explicit foralls but make the Nothing part `(Nothing :: Maybe v)`.

While I'm asking about this, I might as well ask another related question...I was playing around with this KVStore and tried adding a `LookupAllKV :: KVStore k v m [v]` to the definition. This also fails with an ambiguous type error without the plugin enabled, but it actually fails on the template Haskell bit: `makeSem ''KVStore`. Is there any way around this, or would I have to either enable the plugin or manually write out the instances for this?

**Comment by isovector** [comment]
Oh dang! Nice catch -- you just inadvertently found a bug in the error messages! The snippet I posted above is correct, just that the type is now *regular* ambiguous (in the `-XAllowAmbiguousTypes` sense). Turn on `AllowAmbiguousTypes` and it should work as expected.

I suspect this will fix your `LookupAllKV` problem too, but you might be running into #48 instead.

**Comment by cah6** [comment]
FYI made an issue in HIE: https://github.com/haskell/haskell-ide-engine/issues/1264. 

I think you're right in that `LookupAllKV` is running into that phantom parameter issue you linked, as it still fails with `AllowAmbiguousTypes` (with plugin not loaded).

**Comment by isovector** [comment]
Programming is hard! I'll see about fixing #48 tomorrow.

**Comment by isovector** [comment]
Appears to be fixed upstream!

**Comment by fendor** [comment]
It is not fixed upstream yet, but a patch is ready soon!
