### ISSUE TITLE
Rewrite Polysemy.Internal.TH.Effect in terms of th-abstraction

### ISSUE THREAD

**Issue by isovector** [isovector/polysemy#56]
The [`th-abstraction`](http://hackage.haskell.org/package/th-abstraction-0.3.1.0/docs/Language-Haskell-TH-Datatype.html) package gives a significantly nicer view of GADTs. This would make it much easier to fix #48 and any other hidden TH bugs that nobody has run into yet.

**Comment by googleson78** [comment]
I'll try looking at this in the weekend if someone isn't already and it doesn't need to be done asap.

**Comment by isovector** [comment]
I think @TheMatten is currently tackling this!

**Comment by TheMatten** [comment]
Should have written here :smile:

Will make PR when I will have something usable.

**Comment by isovector** [comment]
Fixed by #67
