### ISSUE TITLE
[Question] on integrating with an existing MTL-style library

### ISSUE THREAD

**Issue by cah6** [isovector/polysemy#65]
Been playing around with and enjoying the library but think I could benefit from some general "understanding" help! 

What I wanted to do was implement the [KVStore in polysemy-zoo](https://github.com/isovector/polysemy-zoo/blob/master/src/Polysemy/KVStore.hs) interpreter for Elasticsearch (ES), using Bloodhound (see [here](http://hackage.haskell.org/package/bloodhound-0.16.0.0/docs/Database-V5-Bloodhound-Client.html) for relevant docs). 

My working code that I have so far:
```
esIndex = IndexName "index1"
esMapping = MappingName "mapping"

data ElasticsearchKVError = 
    ResponseParseError Text
  | KnownEsError Text

runKVStoreBloodhound :: FromJSON v
  => Members '[Reader (BHEnv), Lift IO, Error ElasticsearchKVError] r
  => Sem (KVStore k v ': r) a 
  -> Sem (Error ElasticsearchKVError ': r) a
runKVStoreBloodhound = reinterpret $ \case
  LookupKV k    -> do
    bhEnv <- ask 
    reply <- runBH bhEnv $ getDocument esIndex esMapping (DocId "12345")
    case eitherDecode (responseBody reply) of 
      Left err          -> throw $ ResponseParseError (pack err)
      Right esResponse  -> return $ Just esResponse
  UpdateKV k v  -> undefined
```

Note that the above doesn't do /exactly/ what would be expected but I left the rest out since it's unimportant for this question. In any case, I think the signature describes it pretty well: I want to have some way of getting BHEnv so that I can run ES actions, which will run in IO, and want some way to throw errors specific to this domain when things go wrong (and leave that for some upstream interpreter to handle). 

The part I'd like to understand more is the ask/runBH part. I had originally written this outside of the do declaration, like: `LookupKV k -> ask >>= flip runBH do ...` but realized that didn't work when I put in the `throw` statements. I'm assuming this is because by wrapping more (than just the getDocument call) with runBH, I'm now running in MonadBH and have no access to my member constraint methods via `Sem`. 

I'm assuming there's some way around this; ideally I would like to define `ask >>= flip runBH` or similar at the top level of this function, so that inside I have access to all the ES functions as well as my member constraint methods. 

Is this possible? I tried to get this working myself with some combination of raise/lift/etc but could never get it to typecheck. Also I'd be interested in hearing from folks on whether this is a good approach in the first place, or if there's some better way to mix free effects with others, preferably without manually re-writing all the library functions in terms of `Sem`.

**Comment by adamConnerSax** [comment]
Are you just trying to have the ```BH``` monad coexist with your ```Sem r``` monad?  Sandy will have clearer thoughts but:
- You can re-write the effect, as you did, and then "absorb" the mtl style constraint when you need to, that is you can write a function of the form ```absorbMonadBH :: Member (Reader BHEnv) r => (forall m . MonadBH m => m a) -> Sem r a``` which might allow you to call ```getDocument``` more smoothly:
```haskell
newtype MonadBHSem r a = MonadBHSem { unMonadBHSem :: Sem r a }

instance Member (Reader BHEnv) r => MonadBH (MonadBHSem r) where
  getBHEnv = MonadBHSem . ask . unMonadBHSem

absorbMonadBH ::   Member (Reader BHEnv) r => (forall m . MonadBH m => m a) -> Sem r a
absorbMonadBH = unMonadBHSem
```

which you could then use like:
```reply <- absorbMonadBH $ getDocument ...```

Is that what you want?  You could just make a MonadBH instance for ```Member (Reader BHEnv) r => Sem r``` directly but it would be an orphan.  

 Or is it more complicated because BH contains more effects?  In that case you could write a more complicated "absorb" or put ```(Lift BH)``` on your effect list and use ```sendM```.  Which you can definitely do.  You just need to do ```runM``` as the last interpreter before you do ```runBH```.

As an example of the latter, see here:
https://github.com/adamConnerSax/knit-haskell/blob/master/examples/MtlExample.hs

I hope that's helpful!

**Comment by isovector** [comment]
Is this the only effect in which you want to work with Bloodhound? If so, get rid of the `Reader` stuff and just pass it as a parameter:

```haskell
runKVStoreBloodhound :: FromJSON v
  => Members '[Lift IO, Error ElasticsearchKVError] r
  => BHEnv 
  -> Sem (KVStore k v ': r) a 
  -> Sem r a
runKVStoreBloodhound bhEnv = interpret
```

and now you don't need `ask` at all. 

If you want to use the `BHEnv` in other effects too, I'd suggest modeling it as a `Input` instead of a `Reader`!

Notice the return type of `Sem r a` rather than `Sem (Error ElasticsearchKVError ': r) a` -- there's no reason to force users to handle that error effect immediately.

Minor nitpicks aside, I'm not entirely sure what the problem is; are you concerned about how many times you need to call `runBH`? [It doesn't seem to be very expensive](http://hackage.haskell.org/package/bloodhound-0.16.0.0/docs/Database-V5-Bloodhound-Internal-Client.html#t:BH), so I probably wouldn't worry about it too much.

If that's particularly expensive, you can instead `reinterpret`  into a `Lift (BH IO)`, and then immediately run that:

```haskell
runKVStoreBloodhound :: FromJSON v
  => Members '[Lift IO, Error ElasticsearchKVError] r
  => BHEnv 
  -> Sem (KVStore k v ': r) a 
  -> Sem r a
runKVStoreBloodhound bhEnv 
  = interpret (\(Lift bhAction) -> runBH bhEnv bhAction)
  . reinterpret (\case
      LookupKV k    -> do
        reply <- sendM @(BH IO) $ getDocument esIndex esMapping (DocId "12345")
        case eitherDecode (responseBody reply) of 
          Left err          -> throw $ ResponseParseError (pack err)
          Right esResponse  -> return $ Just esResponse
      UpdateKV k v -> ...
    )
```

**Comment by cah6** [comment]
Thanks for the quick responses guys! I definitely think that answers my question -- I just need to play around with it and internalize it a bit more to see exactly what I want. I like that I have multiple choices to consider now!

**Comment by isovector** [comment]
Ps, while @adamConnerSax's solution absolutely will work, I'd suggest saving that technique for application-level problems.

**Comment by adamConnerSax** [comment]
Agreed!  I was imagining this came up/would come up in other places for the author because of "...preferably without manually re-writing all the library functions in terms of Sem."

**Comment by cah6** [comment]
For the main point -- I suppose wrapping each call with `runBH bhEnv` isn't that bad, I was just in the mindset of having done this with MTL before, where having a `MonadBH` constraint gives me access to all these methods and you only have to do `runBH bhEnv` once when you're peeling away the monad transformer layers. Your example with `interpret (\(Lift bhAction) -> sendM $ runBH bhEnv bhAction)` was pretty much what I was looking for -- some way to just describe it once and have access to all the methods that it provides in everything that follows, say if you had some effect that had to call 5 different methods in a row, it would be a bit tedious as the programmer to manually wrap each one.  

However, this seems to break on the `reply <- sendM @(BH IO) ...` bit if I more or less just paste in your code sample. I can paste the entire error message if it helps but it starts with:
```
solveSimpleWanteds: too many iterations (limit = 4)
  Set limit with -fconstraint-solver-iterations=n; n=0 for no limit
  Simples = {[WD] $dMonad_a4eId {0}:: Monad m0 (CNonCanonical),
...
```
I'm pretty sure it's that `sendM` line since it compiles fine if I comment it out. Related, I've gotten a similar error message in other pieces of code -- would it be helpful to create another ticket for those? I assume this is an error message you'd try to avoid since it doesn't give much useful info to the user. 

For the other things you two mentioned...

This is just me playing around with this to learn more right now, so I don't necessarily have more effects that need Bloodhound or not. I initially thought I'd model this as a `Reader` since I wanted to play around with interpretations depending on more interpretations, and figured it would be generally cleaner for some application that used Elasticsearch for a KV store but also in other ways for other effects.

Modeling as `Input` instead of `Reader` is a good point though (since I don't need `local`). After following this through a bit more I think doing it like this works out well, since `BHEnv` has to receive a `Manager` from `Network.HTTP.Client`, which needs IO to create it. So it seems to tie together better if I have a method like `provideBhEnv :: Members '[Lift IO] r => Sem (Input BHEnv ': r) a -> Sem r a` vs creating it in IO when the interpretations are being ran. 

WRT a return type of `Sem (Error ElasticsearchKVError ': r) a` vs `Sem r a`, I admit that I got a little confused on what was required before, so I most definitely appreciate the nitpicks!

Again, thanks for your responses. I'm quite enjoying the library!

**Comment by adamConnerSax** [comment]
I get that error sometimes too! I can usually chase it with a type application or by specifying a type more specifically somehow.

**Comment by isovector** [comment]
@cah6 @adamConnerSax please file a bug if you see that; ideally with a minimal (<20 sloc)  reproduction. I've run into it a few times, and I think it's a genuine type error that's getting swallowed by the plugin.

**Comment by adamConnerSax** [comment]
If I see a good chance to reproduce with minimal lines, I'll do it.  But it's usually in the middle of a muddle...

**Comment by isovector** [comment]
Check out `Polysemy.MTL` in `polysemy-zoo`
