### ISSUE TITLE
How do you use runResource with runErrorInIO?

### ISSUE THREAD

**Issue by ocharles** [isovector/polysemy#75]
I've been trying to verify that `Polysemy.Resource` works correctly with `Polysemy.Error`, but I can't even work out how to compose the two interpreters. I've tried:

```haskell
runM . runErrorInIO runM . runResource (runM . runErrorInIO runM)
```

But the thing given to `runResource` isn't `forall x. m x -> IO x`, because `runErrorInIO` produces `Either e x`. What should I do?

**Comment by ocharles** [comment]
My gut is that these are not actually compatible. I believe, the argument given to `runResource` essentially constraints it to work in only a "`MonadUnliftIO" compatible" stack, and errors are not compatible with that notion (unless you push them all the way down to `IO`).

**Comment by ocharles** [comment]
Ok, sorry for the spam, I guess you can do 

```haskell
(runM . runError runM . runResource ((runM . runError) >=> liftIO . either throwIO return)) (Polysemy.Resource.bracket (liftIO (putStrLn "Hello")) (\_ -> liftIO (putStrLn "Bye")) (Polysemy.Error.throw True))
```

But I can't get that to type check unambigulously.

**Comment by jhenahan** [comment]
I wrote an example for the README for bolting Resource and Error together, but it did take some headscratching. I think the type application in the example was necessary even with the plugin, so you may just need to add one to your error interpreter calls.

**Comment by ocharles** [comment]
Aha, so you have! Thanks, I'll study that too.

**Comment by isovector** [comment]
Try `runM .@ runResource .@@ runErrorInIO @ErrorCall`
