### ISSUE TITLE
Type aliases can't be used to disambiguate input effects (shock, horror)

### ISSUE THREAD

**Issue by sevanspowell** [isovector/polysemy#81]
I wrote some code like this:
```
type S3BucketName = Text
type S3Key = Text

fn
  :: ( Member (Input S3BucketName) r
     , Member (Input S3Key) r
     )
  => Sem r a
fn = do
    bucketName <- input @S3BucketName
    key        <- input @S3Key
...
```

And expected that I could provide the correct values to each input like so:

```
fn
  & runConstInput     @S3BucketName "bucket"
  & runConstInput     @S3Key "key"
```

But this just applies "bucket" to both arguments. In hindsight, this is obvious because S3BucketName and S3Key are just type aliases for Text, making them newtypes instead worked:

```
newtype S3BucketName = S3BucketName Text
newtype S3Key = S3Key Text
```

I know this seems a silly thing to point out (it's expected behavior for type aliases), but it's not something that I expected. I thought it'd be worth pointing out, just in case it can be resolved or documented.

**Comment by isovector** [comment]
Definitely can't be resolved, Haskell completely desugars away type aliases! I'd accept a PR changing the documentation though!

**Comment by sevanspowell** [comment]
"Yo dawg, don't do this"

**Comment by sevanspowell** [comment]
https://github.com/isovector/polysemy/pull/82
