### ISSUE TITLE
Question: Ambiguous use of effect 'Lift' with runTraceIO

### ISSUE THREAD

**Issue by Anrock** [isovector/polysemy#88]
I'm trying to use `runTraceIO`, but getting an error I don't understand. Basically this is all my code verbatim, I think you can safely ignore definition of `Scrub` effect and `reinterpretScrub`, see `runScrubIO` at bottom:
```
data Scrub m a where
  GetAttachments :: Scrub m [Attachment]
  Filter         :: [Attachment] -> Scrub m [Attachment]
  Watch          :: Thread -> Scrub m ()
  Unwatch        :: Thread -> Scrub m ()
  Remember       :: Hash -> Scrub m ()
  Ban            :: Hash -> Scrub m ()
  Download       :: Attachment -> Scrub m ()
  Report         :: Scrub m ()

makeSem ''Scrub

reinterpretScrub :: Sem (Scrub ': m) a -> Sem (State Config ': Trace ': m) a
reinterpretScrub = reinterpret2 $ \case
  Watch t -> modify (\c@Config{watched} -> c{watched = t `S.insert` watched})
  Unwatch t -> modify (\c@Config{watched} -> c{watched = S.delete t watched})
  Remember a -> modify (\c@Config{known} -> c{known = S.insert a known})
  Ban a -> modify (\c@Config{banned} -> c{banned = S.insert a banned})
  Report -> do
    Config{watched, banned, known} <- get
    let bannedCount = show . length $ banned
        knownCount  = show . length $ known
    trace [i|Known files: #{knownCount}, banned: #{bannedCount}, watched threads: #{concatMap show watched}|]
  Filter attachments -> do
    Config{known, banned} <- get
    let undesired = known `S.union` banned
    let filtered = Prelude.filter (\Attachment{md5} -> not $ md5 `member` undesired) attachments
    trace [i|#{length filtered} new files|]
    pure $ filtered

runScrubIO :: Config -> Sem '[Scrub] a -> IO a
runScrubIO config scr = do
  let reinterpreted = reinterpretScrub scr -- Effects: State Config, Trace
      stated = runState config reinterpreted -- Effects: Trace
      traced = runTraceIO stated -- Effects: Lift IO?
      io = runM traced -- Effects: none, it's IO (Config, a)
  (config, res) <- io
  pure res
```

Looks fine to me, but getting unexpected errors:
```
src\Scrub.hs:59:16: error:
    * Ambiguous use of effect 'Lift'
      Possible fix:
        add (Member (Lift IO) '[]) to the context of
          the type signature
      If you already have the constraint you want, instead
        add a type application to specify
          'IO' directly, or activate polysemy-plugin which
            can usually infer the type correctly.
    * In the expression: runTraceIO stated
      In an equation for `traced': traced = runTraceIO stated
      In the expression:
        do let reinterpreted = reinterpretScrub scr
               stated = runState config reinterpreted
               ....
           (config, res) <- io
           pure res
   |
59 |       traced = runTraceIO stated
   |                ^^^^^^^^^^^^^^^^^

src\Scrub.hs:59:16: error:
    * Unhandled effect 'Lift IO'
      Probable fix:
        add an interpretation for 'Lift IO'
    * In the expression: runTraceIO stated
      In an equation for `traced': traced = runTraceIO stated
      In the expression:
        do let reinterpreted = reinterpretScrub scr
               stated = runState config reinterpreted
               ....
           (config, res) <- io
           pure res
   |
59 |       traced = runTraceIO stated
   |                ^^^^^^^^^^^^^^^^^
```
I've tried adding `@IO` to both `runM` and `runTraceIO`, adding `Member (Lift IO)` constraints and every variation of it, but I can't escape that `Ambiguous use of effect 'Lift'`.

Also I don't understand why `Lift IO` is considered unhandled and why at that line exactly. My intuition was that `runTraceIO` basically replaces `Trace` with `Lift IO` and then `Sem '[Lift IO]` is translated to conventional `IO` with `runM`.

**Comment by isovector** [comment]
The problem is that you've said `runScrubIO` takes a `Sem '[Scrub]`. `runTraceIO` says you have a `Lift IO` inside of `r`, but by writing `'[Scrub]` you've said `r` is `'[]`.

Solution: `runScrubIO :: Config -> Sem '[Scrub, Lift IO] a -> IO a`.

**Comment by isovector** [comment]
That being said, the error message could be more helpful in this case!

**Comment by Anrock** [comment]
@isovector that works, thank you! 

Shouldn't `runTraceIO` replace `Trace` with `Lift IO` instead of requiring `Lift IO` to be in effect list in advance? It's seems kinda wrong/strange/counter-intuitive that I have to have `Lift IO` in list of effects of otherwise pure monad that is taken as argument, because somewhere down the line effect in this monad is reinterpreted specifically.

**Comment by isovector** [comment]
This is more a question of convenience rather than correctness. If we _replace_ `Trace` with `Lift IO`, it means we need to handle the `IO` immediately, which doesn't compose very well if we also want to do other things in `IO`. 

Instead, if we just require that `Lift IO` is _somewhere_ in the stack, that somewhere could be immediately next (like if we replaced it), or it could be anywhere else. This second case is significantly more useful for all intents and purposes, and so that's why we choose it.

The heuristic is this:

* If you want to _immediately_ run some other interpreters as part of your interpreter, use `reinterpret*`
* Otherwise use `interpret*`

**Comment by Anrock** [comment]
Thanks for explanation. I'll check if `reinterpret` will be more convenient in my case.
