### ISSUE TITLE
Include polysemy.cabal?

### ISSUE THREAD

**Issue by zarybnicky** [isovector/polysemy#9]
I couldn'ŧ wait for the release so I tried to see whether I could use this package in GHCJS (where I do most of my development). My build system (nix) however sees that there's no cabal file and tries to compile and use GHCJS's hpack, which is not possible as the package 'yaml' doesn't work there.

Do you think you could include the cabal file? I think stack regenerates it automatically whenever package.yaml changes, so it shouldn't add any more work...

**Comment by isovector** [comment]
Fixed in a03eb2c

**Comment by zarybnicky** [comment]
Thanks :)
Now on to figuring out how to build reflex-platform with GHC 8.6...

**Comment by isovector** [comment]
Good luck! Let me know how it goes :)
