### ISSUE TITLE
TH changes necessary for GHC HEAD

### ISSUE THREAD

**Issue by Infinisil** [isovector/polysemy#99]
While testing out GHC HEAD ([9bc10993bb](https://gitlab.haskell.org/ghc/ghc/commit/9bc10993bb300d3712b0f13ec6e28621d75d4204)), I had to do a small change for the TH part of polysemy to compile. I'm just using this issue in case somebody in the future needs it. Can't make a PR because it's an incompatible change (would have to use CPP). Here's the change:

```diff
diff --git a/src/Polysemy/Internal/TH/Effect.hs b/src/Polysemy/Internal/TH/Effect.hs
index 2192ce9..7e44c75 100644
--- a/src/Polysemy/Internal/TH/Effect.hs
+++ b/src/Polysemy/Internal/TH/Effect.hs
@@ -133,8 +133,10 @@ genFreer should_mk_sigs type_name = do
   dt_info    <- reifyDatatype type_name
   cl_infos   <- traverse (mkCLInfo dt_info) $ datatypeCons dt_info
   tyfams_on  <- isExtEnabled TypeFamilies
-  def_mod_fi <- sequence [ TySynInstD ''DefiningModule
-                             . TySynEqn [ConT $ datatypeName dt_info]
+  def_mod_fi <- sequence [ TySynInstD
+                             . TySynEqn Nothing (AppT
+                                (ConT ''DefiningModule)
+                                (ConT $ datatypeName dt_info))
                              . LitT
                              . StrTyLit
                              . loc_module
```

This issue can be closed (it's not really an issue after all).

**Comment by isovector** [comment]
Thanks for the report!

@glguy is this something that is handled via `th-abstraction`?

**Comment by glguy** [comment]
This looks like something you could use [tySynInstDCompat](http://hackage.haskell.org/package/th-abstraction-0.3.1.0/docs/Language-Haskell-TH-Datatype.html#v:tySynInstDCompat) for.

**Comment by isovector** [comment]
Fantastic, thanks!
